language: python
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.4
      - python3.5
      - python3.6
dist: xenial
python:
  - 3.7
cache: pip
install: travis_retry pip install "virtualenv" tox codecov
script: tox -e $TOX_ENV
env:
  - TOX_ENV=django21-py37
  - TOX_ENV=django21-py36
  - TOX_ENV=django21-py35
  - TOX_ENV=django20-py37
  - TOX_ENV=django20-py36
  - TOX_ENV=django20-py35
  - TOX_ENV=django111-py36
  - TOX_ENV=django111-py35
  - TOX_ENV=django111-py34
  - TOX_ENV=django110-py35
  - TOX_ENV=django110-py34
  - TOX_ENV=django19-py35
  - TOX_ENV=django19-py34
  - TOX_ENV=django18-py35
  - TOX_ENV=django18-py34
